# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CRAWL CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: cache npm
      uses: actions/cache@v2.1.5
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: install dependencies
      run: npm i
    - name: cron
      env:
        PERSONAL_TOKEN: ${{ github.token }}
        PUBLISH_REPOSITORY: Riadloc/one-push
      run: |
        REPOSITORY_PATH="https://x-access-token:${PERSONAL_TOKEN}@github.com/${PUBLISH_REPOSITORY}.git"
        sudo chmod -R 777 ./bin/gh-pages.sh
        npm run crawl ${GITHUB_ACTOR} ${PUBLISH_REPOSITORY}
    - run: echo "RUN crawl done"
    
